version: "3.7"

services:
  django-app:
    image: leoshao/django-app:1
    # build: .
    # volumes:
    #   - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    # command: ["./wait-for-it.sh", "mysql:3306"]
    # command: bash -c "./wait-for-it.sh mysql:3306 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "./entrypoint.sh"]

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_PORT: 3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - my-data-volume:/var/lib/mysql
volumes:
  my-data-volume: