apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\leo_shao\Desktop\bin\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: django-app
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\leo_shao\Desktop\bin\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: django-app
    spec:
      containers:
        - args:
            - ./wait-for-it.sh
            - mysql:3306
            - --
            - ./entrypoint.sh
          image: leoshao/django-app:1
          name: django-app
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
