apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\leo_shao\Desktop\bin\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: django-app
  name: django-app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: django-app
status:
  loadBalancer: {}
